package entities;
// Generated Jun 6, 2016 4:32:23 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.TableGenerator;
import org.hibernate.annotations.Generated;

/**
 * Bukutelpon generated by hbm2java
 */
@Entity
@Table(name = "bukutelpon", schema = "public"
)
public class Bukutelpon implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @Column(name = "id", unique = true, nullable = false)
    private int id;
    @Column(name = "nama", length = 50)
    private String nama;
    @Column(name = "nohp", length = 20)
    private String nohp;
    @ManyToOne
    @JoinColumn(name = "id", referencedColumnName = "id_buku", insertable = false, updatable = false)
    private Detail detail;

    public Bukutelpon() {
    }

    public Bukutelpon(int id) {
        this.id = id;
    }

    public Bukutelpon(int id, String nama, String nohp) {
        this.id = id;
        this.nama = nama;
        this.nohp = nohp;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getNama() {
        return this.nama;
    }

    public void setNama(String nama) {
        this.nama = nama;
    }

    public String getNohp() {
        return this.nohp;
    }

    public void setNohp(String nohp) {
        this.nohp = nohp;
    }

    public Detail getDetail() {
        return detail;
    }

    public void setDetail(Detail detail) {
        this.detail = detail;
    }

}
