package entities;
// Generated Jun 6, 2016 4:32:23 AM by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Detail generated by hbm2java
 */
@Entity
@Table(name = "detail", schema = "public"
)
public class Detail implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @Column(name = "id", unique = true, nullable = false)
    private int id;
    @Column(name = "alamat")
    private String alamat;
    @Column(name = "id_buku")
    private Integer idBuku;

    /*@ManyToOne
    @JoinColumn(name = "id_buku", referencedColumnName = "id", insertable = false, updatable = false)
    private Bukutelpon  bukutelpon;*/
    @OneToMany(mappedBy = "detail", cascade = CascadeType.ALL)
    List<Bukutelpon> ls=new ArrayList<Bukutelpon>();

    public Detail() {
    }

    public Detail(int id) {
        this.id = id;
    }

    public Detail(int id, String alamat, Integer idBuku) {
        this.id = id;
        this.alamat = alamat;
        this.idBuku = idBuku;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getAlamat() {
        return this.alamat;
    }

    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }

    public Integer getIdBuku() {
        return this.idBuku;
    }

    public void setIdBuku(Integer idBuku) {
        this.idBuku = idBuku;
    }

    public List<Bukutelpon> getLs() {
        return ls;
    }

    public void setLs(List<Bukutelpon> ls) {
        this.ls = ls;
    }

    

}
